---
language: python
dist: focal
services: docker

env:
  matrix:
    - MOLECULE_DISTRO: debian9
    - MOLECULE_DISTRO: debian10
    - MOLECULE_DISTRO: ubuntu1804
    - MOLECULE_DISTRO: ubuntu2004
    - MOLECULE_DISTRO: centos7
    - MOLECULE_DISTRO: centos8

install:
  - pip install -r test-requirements.txt

script:
  - molecule test

# rename project directory to match Galaxy role name
before_script:
  - cd ../
  - mv ansible-monitoring-plugins bodsch.monitoring-plugins
  - cd bodsch.monitoring-plugins

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
