---

- name: remove python2.pref
  file:
    path: /etc/apt/preferences.d/python2.pref
    state: absent
  when:
    - ansible_os_family | lower == 'debian'

# - name: "create links to python{{ use_python_version }}"
#   file:
#     src: "{{ item.src }}"
#     dest: "{{ item.dest }}"
#     state: link
#   loop:
#     - src: /usr/bin/python{{ use_python_version }}
#       dest: /usr/bin/ python
#     - src: /usr/bin/python{{ use_python_version }}-config
#       dest: /usr/bin/python-config
#     - src: /usr/bin/pydoc{{ use_python_version }}
#       dest: /usr/bin/pydoc
#     - src: /usr/bin/pygettext{{ use_python_version }}
#       dest: /usr/bin/pygettext
#   loop_control:
#     label: "{{ item.src }}"
#   no_log: true
#   ignore_errors: true
#
# - name: set fact for ansible_python_interpreter
#   set_fact:
#     ansible_python_interpreter: /usr/bin/python{{ use_python_version }}

...
