---

- name: install monitoring plugins
  ansible.builtin.package:
    name: "{{ monitoring_plugins }}"
    state: present
  when:
    - monitoring_plugins | default([]) | count > 0

- name: OS specific plugins directory
  when:
    - not ansible_os_family | lower in ['archlinux', 'artix linux']
  block:
    - name: find OS specific plugins directory
      ansible.builtin.find:
        paths: "/usr/lib/nagios,/usr/lib64/nagios"
        file_type: directory
        patterns:
          - "plugins"
        recurse: true
      register: found_directory

    - name: define monitoring_plugins_directory
      ansible.builtin.set_fact:
        monitoring_plugins_directory: "{{
            found_directory.files |
            sort(attribute='path', reverse=True) |
            map(attribute='path') | list | first }}"
      when:
        - found_directory.files is defined
        - found_directory.files | count > 0

    - name: create generic link for {{ monitoring_plugins_directory }} to /usr/lib/monitoring-plugins
      ansible.builtin.file:
        src: "{{ monitoring_plugins_directory }}"
        dest: /usr/lib/monitoring-plugins
        state: link

- name: re-read setup
  ansible.builtin.setup:

...
