---

- name: prepare
  ansible.builtin.include_tasks: prepare.yaml

- name: install
  ansible.builtin.include_tasks: install.yaml

- name: extra plugins
  ansible.builtin.include_tasks: extra_plugins.yaml

- name: fix apt
  ansible.builtin.include_tasks: fix_apt.yaml
#  when:
#    - monitoring_plugins_fix_python_version

...
