---

- name: include OS specific configuration
  ansible.builtin.include_vars: "{{ lookup('first_found', params) }}"
  vars:
    params:
      paths:
        - "vars"
      files:
        # eg. debian-10 / ubuntu-20 / centos-8 / oraclelinux-8
        - "{{ ansible_distribution | lower }}-{{ ansible_distribution_major_version }}.yaml"
        # eg. archlinux-systemd / archlinux-openrc
        - "{{ ansible_distribution | lower }}-{{ ansible_service_mgr | lower }}.yaml"
        # eg. debian / ubuntu / centos / oraclelinux
        - "{{ ansible_distribution | lower }}.yaml"
        # eg. redhat / debian
        - "{{ ansible_os_family | lower }}.yaml"
        # artixlinux
        - "{{ ansible_os_family | lower | replace(' ', '') }}.yaml"
        - default.yaml
      skip: true

- name: python version
  when:
    - monitoring_plugins_fix_python_version
  block:
    - name: detect installed python version
      ansible.builtin.set_fact:
        use_python_version: "{{ ansible_python.version.major }}"

    - name: detect python binary
      ansible.builtin.stat:
        path: "/usr/bin/python{{ use_python_version }}"
      register: python_binary

- name: debian based
  when:
    - ansible_os_family | lower == 'debian'
  block:
    - name: block installation of python2
      ansible.builtin.copy:
        src: apt/preferences.d/python2.pref
        dest: /etc/apt/preferences.d/python2.pref
        mode: 0644

    - name: make sure python3-apt is installed (only debian based)
      ansible.builtin.package:
        name:
          - python3-apt
        state: present

    - name: update apt cache
      block:
        - name: clean apt cache  # noqa command-instead-of-module no-handler
          ansible.builtin.command: |
            apt-get clean
          register: apt_clean
          changed_when: apt_clean.rc != 0
          failed_when: apt_clean.rc != 0
          when: "ansible_version.full is version_compare('2.13', '<')"

        - name: clean apt cache  # noqa args[module]
          ansible.builtin.apt:
            clean: true
          when: "ansible_version.full is version_compare('2.13', '>=')"

- name: install dependencies
  ansible.builtin.package:
    name: "{{ monitoring_plugins_dependecies }}"
    state: present
  when:
    - monitoring_plugins_dependecies is defined
    - monitoring_plugins_dependecies | count > 0

# redhat based
#
- name: redhat based
  when:
    - ansible_os_family | lower == 'redhat'
  block:
    #
    - name: import EPEL GPG key.
      ansible.builtin.rpm_key:
        key: https://archive.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-{{ ansible_distribution_major_version }}
        state: present

    - name: install EPEL repository
      ansible.builtin.yum_repository:
        name: epel
        state: present
        description: Extra Packages for Enterprise Linux {{ ansible_distribution_major_version }} - $basearch
        baseurl: http://download.fedoraproject.org/pub/epel/{{ ansible_distribution_major_version }}/$basearch
        gpgkey: file:///etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL-{{ ansible_distribution_major_version }}
        metalink: https://mirrors.fedoraproject.org/metalink?repo=epel-{{ ansible_distribution_major_version }}&arch=$basearch&infra=$infra&content=$contentdir
        failovermethod: priority
        gpgcheck: 1
        enabled: 1

- name: update package cache
  ansible.builtin.package:
    update_cache: true

- name: define OS related monitoring plugins (archlinux)
  ansible.builtin.set_fact:
    monitoring_plugins: "{{ monitoring_plugins_arch + monitoring_plugins | default([]) }}"
  when:
    - ansible_os_family | lower in ['archlinux', 'artix linux']

- name: define OS related monitoring plugins (debian)
  ansible.builtin.set_fact:
    monitoring_plugins: "{{ monitoring_plugins_debian + monitoring_plugins | default([]) }}"
  when:
    - ansible_os_family | lower == 'debian'

- name: define OS related monitoring plugins (redhat)
  ansible.builtin.set_fact:
    monitoring_plugins: "{{ monitoring_plugins_redhat + monitoring_plugins | default([]) }}"
  when:
    - ansible_os_family | lower == 'redhat'

- name: remove blacklisted plugins
  ansible.builtin.set_fact:
    monitoring_plugins: "{{ monitoring_plugins | difference(monitoring_plugins_blacklist) }}"
  when:
    - monitoring_plugins_blacklist is defined
    - monitoring_plugins_blacklist | count != 0

#- name: get latest system information
#  ansible.builtin.setup:

...
