---
- hosts: all
  any_errors_fatal: false
  environment:
    NETRC: ''

  roles:
    - role: ansible-monitoring-plugins

  pre_tasks:
    - debug:
        msg:
          - "python version       : {{ ansible_python.version.major }}.{{ ansible_python.version.minor }}"

  post_tasks:
    - debug:
        msg:
          - "python version       : {{ ansible_python.version.major }}.{{ ansible_python.version.minor }}"

...
