---
- hosts: all
  any_errors_fatal: false
  environment:
    NETRC: ''

  vars:

    monitoring_plugins_download:
      - url: 'https://gitlab.com/coremedia-as-code/monitoring/monitoring-plugins/raw/master/icinga2/check_coremedia_licenses.py'
        dest: 'check_coremedia_licenses.py'
        checksum: ''
        validate: false
      - url: 'https://raw.githubusercontent.com/bodsch/check_arch_updates/1.0/check_arch_updates'
        dest: 'check_arch_updates'
        checksum: 'sha256:7afa562aaedb63f6e93cfebfa4a9a3ea49fecda62d4dae3d8ff919b76c117c41'

    monitoring_plugins_blacklist:
     - nagios-plugins-mysql

  roles:
    - role: bodsch.monitoring-plugins
