---

- name: converge
  hosts: instance
  any_errors_fatal: false
  become: false

  roles:
    - role: ansible-monitoring-plugins

  # pre_tasks:
  #   - name: python version
  #     debug:
  #       msg:
  #         - "python version       : {{ ansible_python.version.major }}.{{ ansible_python.version.minor }}"
  #
  # post_tasks:
  #   - name: python version
  #     debug:
  #       msg:
  #         - "python version       : {{ ansible_python.version.major }}.{{ ansible_python.version.minor }}"

...
